import Nav from './components/Nav'
import './globals.css'
import { Inter, Source_Code_Pro } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav />
      {children}
      </body>
    </html>
  )
}
